device:
    csr1:
        hostname: sw-1
        ip: 10.0.0.1
        username: admin
        password: admin
        port: 22
        secret: secret
    csr2:
        hostname: sw-2
        ip: 10.0.0.6
        username: admin
        password: admin
        port: 22
        secret: secret
