device:
    sw1:
        csr: cisco_xe
        hostname: sw1
        ip: 10.0.0.1
        username: admin
        password: admin
        port: 22
        secret: secret
    sw2:
        csr: cisco_xe
        hostname: sw2
        ip: 10.0.0.2
        username: admin
        password: admin
        port: 22
        secret: secret
    sw3:
        csr: cisco_xe
        hostname: sw3
        ip: 10.0.0.3
        username: admin
        password: admin
        port: 22
        secret: secret
    sw4:
        csr: cisco_xe
        hostname: sw4
        ip: 10.0.0.4
        username: admin
        password: admin
        port: 22
        secret: secret
    sw5:
        csr: cisco_xe
        hostname: sw5
        ip: 10.0.0.5
        username: admin
        password: admin
        port: 22
        secret: secret
    sw6:
        csr: cisco_xe
        hostname: sw6
        ip: 10.0.0.6
        username: admin
        password: admin
        port: 22
        secret: secret
    sw7:
        csr: cisco_xe
        hostname: sw7
        ip: 10.0.0.7
        username: admin
        password: admin
        port: 22
        secret: secret
    sw8:
        csr: cisco_xe
        hostname: sw8
        ip: 10.0.0.8
        username: admin
        password: admin
        port: 22
        secret: secret
    sw9:
        csr: cisco_xe
        hostname: sw9
        ip: 10.0.0.9
        username: admin
        password: admin
        port: 22
        secret: secret
    sw10:
        csr: cisco_xe
        hostname: sw10
        ip: 10.0.0.10
        username: admin
        password: admin
        port: 22
        secret: secret
